export const ALL_HOTEL_REQUEST = "ALL_HOTEL_REQUEST"
export const ALL_HOTEL_SUCCESS = "ALL_HOTEL_SUCCESS"
export const ALL_HOTEL_FAIL = "ALL_HOTEL_FAIL"

export const BOOK_HOTEL_REQUEST ="BOOK_HOTEL_REQUEST"
export const BOOK_HOTEL_SUCCESS ="BOOK_HOTEL_SUCCESS"
export const BOOK_HOTEL_FAIL ="BOOK_HOTEL_FAIL"

export const HOTEL_DETAIL_REQUEST = "HOTEL_DETAIL_REQUEST"
export const HOTEL_DETAIL_SUCCESS = "HOTEL_DETAIL_SUCCESS"
export const HOTEL_DETAIL_FAIL = "HOTEL_DETAIL_FAIL"

export const CLEAR_ERRORS ="CLEAR_ERRORS";