export const USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL";

export const USER_LOGOUT_REQUEST ="USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS ="USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL ="USER_LOGOUT_FAIL";

export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL ="USER_REGISTER_FAIL";

export const USER_FORGOTPASSWORD_REQUEST ="USER_FORGOTPASSWORD_REQUEST";
export const USER_FORGOTPASSWORD_SUCCESS ="USER_FORGOTPASSWORD_SUCCESS";
export const USER_FORGOTPASSWORD_FAIL ="USER_FORGOTPASSWORD_FAIL";

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const CLEAR_ERRORS = "CLEAR_ERRORS";